# main config for srs.
# @see full.conf for detail config.

max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
daemon              on;
rtmp {
    listen              1935;
}
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.io/lts/en-us/docs/v7/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        # @see https://ossrs.io/lts/en-us/docs/v7/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc off;
        # @see https://ossrs.io/lts/en-us/docs/v7/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp off;
    }

    play{
        gop_cache_max_frames 2500;
    }
}

python_addons {
    enabled on;
    restart 3;  # Default restart each addon process up to 3 times on failure.
    retry_interval 5;  # Default: Wait 5 seconds before retrying to start a failed addon process.
    failure_exit on;  # Default: Exit SRS if any addon process fails after retries.

    addon {
        # Relative path resolved against the config working directory.
        script python_addons/httpbackend_server.py;
        # Optional command line arguments passed to the addon process.
        args "--conf=conf/intra-stream.conf";
        # Optional working directory; default is the config cwd when omitted.
        work_dir ./;
    }
}